spring:
  application:
    name: spring-boot-spring-gateway

server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: true
    fetch-registry: true
