spring:
  application:
    name: SocialLogin
  datasource:
    password: acquah_user
    username: acquah
    url: jdbc:postgresql://localhost:5432/movie_app_users
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_id}
            client-secret: ${google_client_secret}
          github:
            client-id: ${github_id}
            client-secret: ${github_client_id}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: trace
